### ISSUE TITLE
keyError:'IndexBackward' 

### ISSUE THREAD

**Issue by GeorgeBohw** [longcw/pytorch2caffe#11]
When i convert my  model from pytorch to caffe,it meet with the following error:
keyError:'IndexBackward'
What's wrong with it ,anybody can tell me?which layer's problem?

**Comment by longcw** [comment]
This may be caused by `tensor[i]` since this project didn't implement index selection.

**Comment by GeorgeBohw** [comment]
@longcw  thanks ,i check my code now

**Comment by GeorgeBohw** [comment]
@longcw Right!  tensor[i] cause the problem,but now i meet with another problem "KeyError: 'CudaTransferBackward'.Do you know the reason?

**Comment by longcw** [comment]
I am not sure what is `CudaTransferBackward` represent for. But you can try to run the model on CPU for converting. (GPU operations are not supported).

**Comment by GeorgeBohw** [comment]
@longcw  Thanks very much,i try

**Comment by GeorgeBohw** [comment]
@longcw Very Sorry to trouble you!
I have a question,If the **inputs are two variables**,How should i feed the inputs in to function "**pytorch2caffe(input_var, output_var, protofile, caffemodel)**"

**Comment by tongshiwen** [comment]
How to solve the problem about keyError:'IndexBackward' ?

**Comment by tongshiwen** [comment]
> @longcw Right! tensor[i] cause the problem,but now i meet with another problem "KeyError: 'CudaTransferBackward'.Do you know the reason?

How to solve the problem about keyError:'IndexBackward' ?
