### ISSUE TITLE
Conversion doesn't work for DenseNet architectures

### ISSUE THREAD

**Issue by jasiekl** [longcw/pytorch2caffe#2]
Hi @longcw,

I wanted to use the tool for other networks and I found the following problem when I tried to use one of the [DenseNet architectures](https://github.com/pytorch/vision/blob/master/torchvision/models/densenet.py) from Pytorch. I wanted to convert densenet121 model by changing
`m = torchvision.models.inception_v3(pretrained=True, transform_input=False)` to `m = torchvision.models.densenet121()` in your example from [pytorch2caffe.py](https://github.com/longcw/pytorch2caffe/blob/master/pytorch2caffe.py) script. Until classification layer the conversion seems to work, but then and got the following error (just copy-pasting bottom part of the output log):

```
...
converting AvgPool2dBackward483
converting ViewBackward484
converting AddmmBackward484
((1000L,), (1000L, 1024L))
(1000,)
(1000, 4096)
Traceback (most recent call last):
  File "pytorch2caffe.py", line 398, in <module>
    os.path.join(output_dir, 'densenet121-pytorch2caffe.caffemodel'))
  File "pytorch2caffe.py", line 95, in pytorch2caffe
    convert_layer(output_var.grad_fn)
  File "pytorch2caffe.py", line 91, in convert_layer
    save_fc2caffe(weights, biases, params[parent_name])
  File "pytorch2caffe.py", line 111, in save_fc2caffe
    fc_param[0].data[...] = weights.numpy()
ValueError: could not broadcast input array from shape (1000,1024) into shape (1000,4096)
```
Somehow the 2nd dimension of the array to paste in weights is 4x larger than its substitute (this is also true for other DenseNet architectures tested - 161, 169 and 201). Any ideas on what goes wrong? 

Thanks in advance for any help.

**Comment by longcw** [comment]
@jasiekl Sorry for late.
You have to set the same input size as the original model if the network contains FC layers.
So you can set `input_var = Variable(torch.rand(1, 3, 224, 224))` for Densnet.

**Comment by shiruipeng1985** [comment]
Have you solved the problem?@ jasiekl
