### ISSUE TITLE
which version of pytorch and torchvision should be used? advice needed

### ISSUE THREAD

**Issue by dzyjjpy** [longcw/pytorch2caffe#26]
which version of pytorch and torchvision should be used? advice needed.
I tried torch 1.0.0 and 0.3.1
torchvision: 0.2.2, 0.2.0
errors occured:  keyError: 'data'
net.blobs['data'].data[...] = input_data

dose anyone have advice? 
And I have own model trained by torch 0.3.1, torchvision 0.2.0
want to convert to caffemodel for other engine to accelerate.

**Comment by longcw** [comment]
This should work with torch 0.3.1 or 0.2. Some layers may not well supported. Please check the demo first to see if it works.

**Comment by dzyjjpy** [comment]
when use torch 0.3.1, vision0.2.0, it can download the inceptionv3 model
it shows network initialization done.
but in File demo.py, line 49, in <module>
         net.blobs['data'].data[...] = input_data
keyError: 'data'

**Comment by longcw** [comment]
This line is to fill the data for caffe. So it's not the problem of pytorch.

**Comment by dzyjjpy** [comment]
@longcw  I reinstall torch 0.3.1, solve the issue above. But another error occured when running demo.py
line 165, in add_layer
      **layer['type'] = layer_dict[parent_type]
KeyErrors: 'ExpandBackward'**

And it might be caused by layers not supported.I find same problem in issue. 
[https://github.com/longcw/pytorch2caffe/issues/6](url)
**However , my CUDA is 9.2, I cannot install pytorch==0.2.0
Is there any other ways to solve this issue without reinllation for pytorch==0.2.0?**

**Comment by dzyjjpy** [comment]
Finally solved by installing torch 0.2.0 and torchvision 0.1.8.
will try my own model trained based torch 0.3.1
